[[redirects]]
  from = "/api.openweathermap.org/*"
   to = "https://api.openweathermap.org/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200