[[redirects]]
  from = "/api.openweathermap.org/*"
   to = "https://api.openweathermap.org/:splat"
  status = 200
  force = true
  signed = "8496070a6ed3bd27bd80c6c4595509b1"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200